"use strict";
let texto = "hola";
let numero = 555;
let trueFalse = true;
let deTocho = 555;
deTocho = "aaa";
let arrayTexto = ["fff", "ggg"];
let arrayNumero = [555, 555];
let arrayBool = [true, false];
let arrayDeTocho = [true, "aaa", texto, deTocho];
